CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  payment_code VARCHAR(40) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  payment_method ENUM('COD', 'BANK_TRANSFER', 'E_WALLET', 'CREDIT_CARD') NOT NULL,
  provider VARCHAR(50) NOT NULL,
  status ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED', 'REFUNDED') NOT NULL DEFAULT 'PENDING',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  currency_code CHAR(3) NOT NULL DEFAULT 'VND',
  checkout_url VARCHAR(500) NULL,
  qr_content TEXT NULL,
  deep_link VARCHAR(500) NULL,
  gateway_transaction_id VARCHAR(120) NULL,
  gateway_reference VARCHAR(120) NULL,
  failure_reason VARCHAR(255) NULL,
  refund_reason VARCHAR(255) NULL,
  metadata_json TEXT NULL,
  expires_at TIMESTAMP NULL,
  paid_at TIMESTAMP NULL,
  refunded_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE KEY uq_payments_code (payment_code),
  INDEX idx_payments_order_created (order_id, created_at),
  INDEX idx_payments_user_created (user_id, created_at),
  INDEX idx_payments_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  payment_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  status ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED', 'REFUNDED') NOT NULL,
  note VARCHAR(500) NULL,
  payload_json TEXT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_events_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_events_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_payment_events_payment_created (payment_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
