ALTER TABLE orders
  MODIFY COLUMN status ENUM(
    'PENDING_PAYMENT',
    'PLACED',
    'CONFIRMED',
    'PACKED',
    'SHIPPED',
    'DELIVERED',
    'COMPLETED',
    'CANCELLED',
    'RETURN_REQUESTED',
    'RETURNED',
    'REFUNDED'
  ) NOT NULL DEFAULT 'PENDING_PAYMENT';

ALTER TABLE orders
  MODIFY COLUMN payment_method ENUM('COD', 'BANK_TRANSFER', 'E_WALLET', 'CREDIT_CARD') NOT NULL DEFAULT 'E_WALLET';
