CREATE TABLE IF NOT EXISTS public_content_revision (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO public_content_revision (id, revision)
VALUES (1, 1)
ON DUPLICATE KEY UPDATE revision = revision;
